### ISSUE TITLE
Error: Call to undefined function entity_language

### ISSUE THREAD

**Issue by shabibalm** [backdrop-contrib/commerce#1]
hello 
this error in page 
backdropcms/admin/commerce/products/add/

`Error: Call to undefined function entity_language() in commerce_product_product_form() (line 44 of /home/******/public_html/backdropcms/modules/commerce/modules/product/includes/commerce_product.forms.inc).`

and 
page url = backdropcms/admin/commerce/config

Warning: uasort() expects parameter 2 to be a valid callback
`Warning: uasort() expects parameter 2 to be a valid callback, function 'backdrop_sort_weight' not found or invalid function name in commerce_checkout_panes() (line 612 of /home/***/public_html/backdropcms/modules/commerce/modules/checkout/commerce_checkout.module).`

thanks

**Comment by elisseck** [comment]
There has been a significant overhaul to this port to Backdrop. You'll find the previous code in the 1.x-1.x-old branch.

I took a quick look and test, and I think these may be resolved. Please feel free to re-open the issue if they are not!
