### ISSUE TITLE
_element_validate_integer_positive - not found or invalid

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/commerce#13]
In `commerce_product_reference_field_widget_settings_form` there's a call to `_element_validate_integer_positive` which was removed in Backdrop. Instead change the form field type to `number`. https://docs.backdropcms.org/node/43955

**Comment by herbdool** [comment]
Got a PR https://github.com/backdrop-contrib/commerce/pull/14

**Comment by elisseck** [comment]
Thank you! Looks good.
