### ISSUE TITLE
Warning: Undefined variable $entity_id

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/commerce#15]
Getting this error when viewing an order: "Warning: Undefined variable $entity_id in include() (line 46 of /app/httpdocs/core/modules/entity/templates/entity.tpl.php)."

![2024-10-17 15 38 02 bd3 lndo site 0cde6610f68e](https://github.com/user-attachments/assets/df4b6d53-19b2-418f-a7ce-09c3e6006bec)

**Comment by herbdool** [comment]
Even though its using core's `entity.tpl.php` it's not calling `template_preprocess_entity()`. So either need to get it to use `entity_plus.tpl.php` or figure out how to pass `$entity_id` to it.

**Comment by elisseck** [comment]
Thank you for reporting! There was some old code overriding the template preprocess entity that I don't think is relevant any longer. See referenced commit.
