### ISSUE TITLE
Warning: Undefined property: CommerceProduct::$langcode in CommerceProductInlineEntityFormController->entityForm()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/commerce#16]
I'm testing with Inline Entity Form with a product reference field:

> Warning: Undefined property: CommerceProduct::$langcode in CommerceProductInlineEntityFormController->entityForm() (line 198 of /app/httpdocs/modules/inline_entity_form/includes/commerce_product.inline_entity_form.inc).

**Comment by elisseck** [comment]
I was able to reproduce this, and I think it's a good idea to just follow the Backdrop core Node example for entities when we find things that other modules might expect to exist.

471507cb15c473cb6cddac862939ce41c2283ec8 should resolve this issue.
