### ISSUE TITLE
rules_config_delete() has been renamed

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/commerce#3]
In https://github.com/backdrop-contrib/rules/issues/89, it was noted that the function `rules_config_delete()` happens to have the name that makes it a hook invocation of `hook_config_delete()`, which it was not intended to be. This causes problems in entirely unrelated modules when they try to invoke that hook. Therefore, that function within the Rules module has been renamed to `rules_configuration_delete()` in the version of Rules that will be released on or around 2022-01-15.

That function is called within `commerce_tax_ui.module`, so this needs to be updated to work with the newer versions of Rules.

See also https://github.com/backdrop-contrib/ubercart/issues/305.

**Comment by elisseck** [comment]
There has been a significant overhaul to this port to Backdrop. You'll find the previous code in the 1.x-1.x-old branch.

I took a quick look and I believe this has been resolved. Please feel free to re-open the issue if it is not!
