### ISSUE TITLE
Fatal error in PHP 7.0 and 7.1: buildContent() methods

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/commerce#4]
As reported in Entity Plus https://github.com/backdrop-contrib/entity_plus/issues/117 , core's EntityControllerInterface::buildContent() now type-hints its first argument to EntityInterface $entity. Since `EntityPlusControllerInterface::buildContent()` and all the controllers that implement it DON'T type-hint the first argument, we have a method definition mismatch fatal error in PHP 7.0 and 7.1, and possibly others (7.3 and 7.4 seem to not care).

Commerce overrides EntityPlusController::buildContent() and as such, you need to type-hint the first argument as `EntityInterface` to avoid this fatal error. This was fixed in Entity Plus already, but needs to be fixed in all overrides of buildContent.

**Comment by elisseck** [comment]
Thank you for reporting this ages ago! I would not have run into this with these older versions of PHP. Still worth fixing just in case, I don't think this is hurting anything (although I really wish tests were working to be sure).

Should be fixed in 59c5c84be16009a74728e9ffe24acf6cb68f47e3
