### ISSUE TITLE
commerce_file_field_insert() and commerce_file_field_update() should check if $items is false

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/commerce#8]
> Warning: foreach() argument must be of type array|object, bool given in BackdropCommerceEntityController->commerce_file_field_insert() (line 272 of /app/httpdocs/modules/commerce/includes/commerce.controller.inc).

It seems that commerce_file_field_insert() is getting the `$items` loaded by `field_get_items()` but not checking if there are no items of that field type. Probably can just skip if there are no items.

**Comment by elisseck** [comment]
Thank you! I was able to reproduce this and it should be resolved in 5da8eaf5625bc784b0075a160ed07f2105bfca45

**Comment by herbdool** [comment]
@elisseck I added a PR to also update it for `commerce_file_field_update()`. In this case it's updating the attached files and might get passed NULL which should be treated as an empty array to confirm all files have been removed.
