### ISSUE TITLE
Fatal error: commerce_product_ui_config_info() is a duplicate of commerce_product_config_info() 

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/commerce#9]
They both are trying to define the same config `commerce_product.settings`. Delete the one in `commerce_product_ui`.

And while you're there, consolidate `commerce_product_ui_autoload_info` and `commerce_product_autoload_info`

**Comment by elisseck** [comment]
Thank you for reporting! I'm not sure how I didn't encounter a fatal with that one yet... but it should be resolved in 9e597a536a9b6711f3612dbab3c9a55268b55f83
